A/Anton_and_Danik/anton_and_danik.cpp
C++ Solution for https://github.com/sidanand67/Competitive-Programming/issues/3
=> Add Anton_and_Danik in C++

A/Bear_and_Big_Brother/Bear_and_Big_Brother.cpp
@sidanand67 I have added the C++ program regarding issue https://github.com/sidanand67/Competitive-Programming/issues/5 .
I also have added relevant comments. Thanks
=> C++ program for bear and big brother added

A/Gravity_Flip/ikjot-2605.cpp
Please verify, here is submission link : http://codeforces.com/submissions/ikjot_2605
=> Added c++ solution for Gravity Flip

B/Caisa_and_Pylons/ikjot-2605.cpp
Please verify, here is submission link : http://codeforces.com/submissions/ikjot_2605
=> Added c++ solution for Caisa and Pylons

A/Word/MayankAg20.cpp
Please merge this if it is alright.
=> Added Word folder with working CPP code

A/Boy_or_Girl/Gurvir-Sandhar.js
js solution to Boy_or_Girl problem
=> added js solution for Boy_or_Girl

A/Boy_or_Girl/Gurvir-Sandhar.cpp
=> added cpp solution for Boy_or_Girl

A/Stones_on_the_Table/imsubhra.cpp
=> Added Stones on the table

A/Team/rsrahul1000.cpp
- Team
[A Team Problem Statement](https://codeforces.com/problemset/problem/231/A)
#57
=> Add: Problem 231A, A. Team, codeforces solution in c++

A/Anton_and_Danik/krishremya.cpp
=> Anton and Danik in cpp

A/Stones_on_the_Table/Arsenic.cpp
Issue #55 
language used = C++
folder location = A -> Stones_on_the_Table -> Arsenic.cpp
[here](https://codeforces.com/contest/266/submission/94887033) is the link to my accepted solution on code forces.
=> A -> Stones_on_the_Table -> +Arsenic.cpp

B/Cormen_the_best_friend_of_man/robin07.cpp
[Problem Link](https://codeforces.com/contest/732/problem/B)
One of the problem from given sheet
=> cormen_best_friend_of_man_cpp

A/Die_Roll/omarr45.cpp, A/Sereja_and_Dima/omarr45.cpp, A/Sereja_and_Dima/omarr45.java, B/Sum_of_Digits/omarr45.cpp
added solutions for "Sereja_and_Dima" in both cpp and java
added solution for "Sum_of_Digits" in cpp only
Please accept the PR
Thanks!
=> Solutions for Sereja_and_Dima and Sum_of_Digits and Die_Roll

A/Team/utkarsh48.py
#57 
python implementation of the given question. Thanks for assigning.😊
=> Added 'team' solution in python

A/Stones_on_the_Table/deepanshuoct12.cpp
I have read all the guidelines for contributing to this repository. I have used C++ language to solve the problem A Stones on the table
=> A Stones on the table solved by deepanshuoct12

B/Sum_of_Digits/Divyanshu.c
Added "Sum_of_Digits" solution in c
=> Added "Sum_of_Digits" solution in c

A/Autocomplete/omarr45.cpp
I've added the solution for codeforces A53 that is in the sheet.
Please review and accept
Thanks
=> Added "Autocomplete" solution in cpp

B/Burglar_and_Matches/MananOO12.cpp
#29 
Added a simpler solution to problem 16B in C++
Please check.
=> Added Problem 16B simpler solution

A/IQ_Test/omarr45.cpp, A/Watermelon/omarr45.cpp
I've added the solution for codeforces A-4 problem
Please review and accept
Thanks!
=> Added "Watermelon" solution in cpp

C1/Towers/Shashank2409.cpp
I have added the code for a C1 problem named "Towers".
=> Added code for C1 -> Towers

A/Beautiful_Matrix/Spolutrean.java
=> BeautifulMatrix on Java

A/Anton_and_Danik/Spolutrean.java
=> AntonAndDanik on java

A/Team/kritika23111.py
Added solution of issue #57  Team in python language
=> kritika2311.py

A/Team/shivjaiswal-coder.c
Written the solution in C language with quality comments
=> updated in c

C1/Boredom/watch24hrs-iiitd.py
Hi! ✋ 
This is referenced to C1 category problem Boredom at codeforces.com.
Submission Link: https://codeforces.com/contest/456/submission/94938899
All feedbacks/reviews are welcomed!
=> Solved Boredom (https://codeforces.com/contest/456/problem/C) in Python3

Algorithms/3_Sum/Description.txt, Algorithms/3_Sum/rks-69.java, Algorithms/Next_Permutation/Description.txt, Algorithms/Next_Permutation/rks-69.java, Algorithms/Spiral_Matrix/Description.txt, Algorithms/Spiral_Matrix/rks-69.java, Algorithms/Two_Sum/Description.txt, Algorithms/Two_Sum/rks-69.java
Merge the Pull Request to Algorithms
=> Added the Algorithms Folder and added four other folders in it

A/Anton_and_Danik/Agrawal-Lalit.cpp
clear terminologies and variable names are added.
=> A->Anton and Danik updated cpp file

A/Magnets/GarvitBanga.js, B/Burglar_and_Matches/GarvitBanga.js
Javascript Solution to Magnets #41
=> Javascript  Solution to Magnets #41

D1/Gifts_by_the_List/TheAnshul756.cpp
There were not many problems from the D1 section, so I contributed one solution of my own. I  have submitted this solution and got Accepted on Codeforces. Submission: [94924984](https://codeforces.com/contest/681/submission/94924984)
=> Add Gifts by the List in C++

A/Word/japoncio3k.js
Solved problem Word from the A difficulty
=> Problem: A - Word

B/Sum_of_Digits/Aryaniiit002.cpp, B/Sum_of_Digits/Sum of Digits.cpp
=> Added 1 .cpp file 

A/Word/chtnnh.py
=> Add chtnnh.py to Word

A/Gravity_Flip/Spolutrean.java
=> GravityFlip on Java

Algorithms/3_Sum/kapilsharmaks.cpp
I have written a c++ code for 3 sum and added it to repository.
=> Added C++ program of 3 sum

A/Anton_and_Danik/chtnnh.c
=> Add chtnnh.c to Anton_and_Danik

A/Bear_and_Big_Brother/Vanshikaa00.java
Hi @sidanand67 Added solution for bear and big brother problem in java
=> Bear and Big brother in java

Algorithms/Next_Permutation/kapilsharmaks.cpp
I have added c++ code file to Next_Permutation.
=> Added c++ code file to Next_Permutation

B/Caisa_and_Pylons/Spolutrean.java
=> CaisaAndPylons on Java

A/Petya_and_strings/chtnnh.py
=> Add chtnnh.py to Petya_and_strings

A/Boy_or_Girl/chtnnh.py
=> Add chtnnh.py to Boy_or_Girl

A/Magnets/chtnnh.cpp
=> Add chtnnh.cpp to Magnets

A/Vanya_and_Fence/chtnnh.c
Kindly add the hacktoberfest-approved label when merging :D
=> Add chtnnh.c to Vanya_and_Fence

A/IQ_Test/fazeel.py, A/Watermelon/fazeel.py
=> A >iq test >fazeel

A/Watermelon/fazeel.py
This solution got __Accepted__ on Codeforces
=> Added watermelon.py

Algorithms/Spiral_Matrix/kapilsharmaks.cpp
=> c++ code file added

D3/The_Bottom_of_a_Graph/stephenvincent27.cpp
=> Add C++14 code for 'The Bottom of a Graph' in D3

A/Stones_on_the_Table/Fazeel007.py
=> A->stones_on_the_table->Fazeel.py

D3/Test/stephenvincent27.cpp
Verified on UVa Online Judge, gets AC.
=> Add C++14 code for 'Test' in D3

D3/Fedor_and_Essay/stephenvincent27.cpp
=> Add C++14 code for 'Fedor and Essay' in D3

B/Coins/ghsayan.cpp
C++ code for problem: Coins (B)
=> Added solution for B - coins

D3/Theseus_and_Labyrinth/stephenvincent27.cpp
=> Add C++14 code for 'Theseus and Labyrinth' in D3

D3/Cunning_Gena/stephenvincent27.cpp
=> Add C++14 code for 'Cunning Gena' in D3

B/Burglar_and_Matches/tharani247.cpp
Hii, I added my code this repo
=> Added code for Burglar_and_Matches

A/Anton_and_Danik/DivyanshSrivastava04.cpp, A/Sereja_and_Dima/DivyanshSrivastava04.cpp
C++ code for solutions of two problems.
=> Added solutions for Sereja_and_Dima and Anton_and_Danik

A/Bear_and_Big_Brother/DivyanshSrivastava04.cpp
C++ code for A/Bear_and_Big_Brother
=> Added solution for problem Bear and Big Brother

Algorithms/Majority_Element/ninja.py
=> Algorithms -> majority-element -> ninja.py

A/Vanya_and_Fence/DivyanshSrivastava04.cpp
Added C++ solution for A/Vanya_and_Fence.
=> Solution for problem "Vanya and Fence"
